# Generated by Django 4.2.7 on 2023-12-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DM_emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departement',
            new_name='Department',
        ),
    ]
