# Generated by Django 4.2.7 on 2023-12-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_emp_app', '0002_rename_departement_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='E100', max_length=10, primary_key=True, serialize=False),
        ),
    ]
